/* The reference architecture of the PPA appbook, as the running application is built. */
const PPA_REFARCH = {
  tiers: [
    { id: "people", title: "People and channel", note: "one owner, one page" },
    { id: "control", title: "Control plane", note: "the harness owns the loop, the gate and the clock" },
    { id: "models", title: "Models", note: "one reasons, one decides" },
    { id: "tools", title: "Tools and systems of record", note: "an allowlist in front of everything that can act" },
    { id: "data", title: "Data and state · Oracle AI Database 26ai", note: "one schema per owner" },
    { id: "observe", title: "Observability", note: "runs, traces, audit, notifications" },
  ],
  components: [
    { id: "owner", tier: "people", col: 0, kind: "person", name: "Owner", tech: "asks, approves, is briefed", note: "The person the assistant works for. Types requests, decides at the approval gate, receives briefs and notifications." },
    { id: "browser", tier: "people", col: 1, kind: "channel", icon: "browser", name: "Appbook page", tech: "vanilla JS · server-sent events", note: "The assistant view: chat with a live trace, approval cards, agenda, tasks, timers; fourteen chapters; the data explorer." },
    { id: "api", tier: "control", col: 1, kind: "control", icon: "api", name: "Appbook API", tech: "FastAPI · uvicorn", note: "One typed request per turn, resume with a decision, status for every chapter, events for the page." },
    { id: "loop", tier: "control", col: 2, kind: "control", icon: "loop", name: "Assistant loop", tech: "LangGraph · 7 nodes", note: "assemble_context → call_model → dispatch_tools → draft_effects → human_review → apply_effects → persist. Append-only context; a fixed system prompt and tool list for the life of a conversation." },
    { id: "gate", tier: "control", col: 3, kind: "gate", name: "Approval gate", tech: "interrupt() · Command(resume)", note: "A gated tool is drafted, not run. The run pauses; the owner's decision resumes the same run, also after a restart." },
    { id: "clock", tier: "control", col: 4, kind: "control", icon: "timer", name: "Runtime for time", tech: "scheduler thread · triggers · practice clock", note: "Focus timers on the real clock; morning brief, end-of-day wrap and weekly review on schedules; meeting prep and VIP mail as event triggers. Jobs live in the database and survive a restart." },
    { id: "skills", tier: "control", col: 0, kind: "tool", icon: "skills", name: "Skills", tech: "7 manifests · progressive disclosure", note: "Small manifests travel in every turn; a skill's full body is loaded only when the model asks for it." },
    { id: "claude", tier: "models", col: 2, kind: "model", name: "Claude Opus 5.5", tech: "adaptive thinking · prompt cache", note: "Reasons, plans and writes. Sees the assembled context and every tool on every turn, so the prefix stays cached and earlier reasoning stays valid." },
    { id: "jev", tier: "models", col: 3, kind: "decide", name: "Jev · System One", tech: "Typesafe API · noul and choice", note: "Is this email an attack? Which evidence is worth reading? Answered with a probability in a third of a second; the harness owns the threshold and falls back to the tripwire and search order without a key." },
    { id: "tools", tier: "tools", col: 2, kind: "tool", name: "Trusted tools", tech: "allowlist · effect tiers · wrapper", note: "Thirty-nine tools: automatic reads, gated effects. External text reaches the model wrapped as data." },
    { id: "mcp", tier: "tools", col: 3, kind: "tool", icon: "mcp", name: "Workspace gateway", tech: "MCP over HTTP · mail, calendar, notes", note: "Three MCP servers over the practice workspace (a real public mailbox replayed against a clock) or your own accounts. Safe mode holds outbound messages as drafts." },
    { id: "tavily", tier: "tools", col: 4, kind: "external", icon: "search", name: "Tavily web search", tech: "optional", note: "The web_search tool, when a key is set." },
    { id: "memory", tier: "data", col: 0, kind: "store", icon: "memory", name: "Memory and scratch pad", tech: "ppa_memories · scratch files · promotion queue", note: "Long-term memory with forgetting; the workday scratch pad; end-of-day promotion with content-hash dedupe." },
    { id: "state", tier: "data", col: 1, kind: "store", icon: "database", name: "Harness tables", tech: "ppa_tasks · focus · jobs · contacts", note: "Tasks with a source link, focus sessions, armed jobs, notifications, the skill and tool registries." },
    { id: "checkpoints", tier: "data", col: 2, kind: "store", icon: "checkpoint", name: "Checkpoints", tech: "AsyncOracleSaver · one thread per conversation", note: "Every step of every run. A paused run resumes from here." },
    { id: "audit", tier: "data", col: 3, kind: "store", icon: "shield", name: "Action audit", tech: "ppa_action_audit · approvals · delivery", note: "Each drafted action, its decision, its execution and its delivery, kept apart." },
    { id: "decisions", tier: "data", col: 4, kind: "store", icon: "decide", name: "Decision log", tech: "ppa_decision_log", note: "Every question put to System One with its time and tokens." },
    { id: "runs", tier: "observe", col: 2, kind: "observe", icon: "ledger", name: "Runs and traces", tech: "ppa_agent_runs · thread messages · spans", note: "The request, the answer, every node and tool call with its timing and tokens." },
    { id: "notify", tier: "observe", col: 4, kind: "observe", icon: "bell", name: "Notifications", tech: "ppa_notifications · SSE · browser", note: "What a timer or a routine produced, delivered to the page and, if allowed, the browser." },
    { id: "explorer", tier: "observe", col: 1, kind: "observe", icon: "vector", name: "Data explorer", tech: "read-only · every harness table", note: "Docked under every chapter; a second source is a read-only window on the notebook's schema." },
  ],
  flows: [
    { id: "ask", from: "owner", to: "browser", label: "a request", kind: "request" },
    { id: "post", from: "browser", to: "api", label: "POST /api/assistant/turn", kind: "request" },
    { id: "run", from: "api", to: "loop", label: "agent.run(request)", kind: "control" },
    { id: "manifests", from: "skills", to: "loop", label: "manifests, then one body on demand", kind: "data" },
    { id: "recall", from: "loop", to: "memory", label: "recall · write", kind: "store" },
    { id: "reason", from: "loop", to: "claude", label: "context + tools → text and tool calls", kind: "data" },
    { id: "decide", from: "loop", to: "jev", label: "closed questions → probabilities", kind: "control" },
    { id: "dispatch", from: "loop", to: "tools", label: "automatic tools", kind: "control" },
    { id: "gateway", from: "tools", to: "mcp", label: "allowlisted reads and writes", kind: "data" },
    { id: "web", from: "tools", to: "tavily", label: "web_search", kind: "data" },
    { id: "state", from: "tools", to: "state", label: "tasks · focus · jobs", kind: "store" },
    { id: "checkpoint", from: "loop", to: "checkpoints", label: "checkpoint after every node", kind: "store" },
    { id: "draft", from: "loop", to: "gate", label: "draft_effects → interrupt()", kind: "control" },
    { id: "card", from: "gate", to: "browser", label: "approval card (SSE)", kind: "data" },
    { id: "decision", from: "browser", to: "gate", label: "approve · reject", kind: "request" },
    { id: "resume", from: "gate", to: "loop", label: "Command(resume) → apply_effects", kind: "control" },
    { id: "audit", from: "gate", to: "audit", label: "decision · execution · delivery", kind: "store" },
    { id: "logdecision", from: "jev", to: "decisions", label: "time · tokens", kind: "store" },
    { id: "arm", from: "clock", to: "state", label: "armed jobs, in the database", kind: "store" },
    { id: "fire", from: "clock", to: "loop", label: "a job fires: a routine turn", kind: "event" },
    { id: "notify", from: "clock", to: "notify", label: "notification", kind: "event" },
    { id: "toast", from: "notify", to: "browser", label: "SSE · browser notification", kind: "event" },
    { id: "trace", from: "loop", to: "runs", label: "run · trace · messages", kind: "store" },
    { id: "live", from: "runs", to: "browser", label: "live trace (SSE)", kind: "event" },
    { id: "explore", from: "explorer", to: "state", label: "read-only rows", kind: "data" },
  ],
  runs: [
    { id: "brief", title: "Prepare my morning brief", blurb: "One typed request through the loop: memory, skills and governed definitions in the first message, one skill loaded on demand, the inbox read through MCP and screened by System One, an answer in about fifteen seconds.",
      steps: [
        { flow: "ask", note: "\"Prepare my morning brief.\"" },
        { flow: "post", note: "The page posts the message with its conversation id." },
        { flow: "run", note: "agent.run: a new run in this conversation.", state: "ppa_agent_runs: running" },
        { flow: "recall", note: "assemble_context: standing memories and recalled memories by meaning." },
        { flow: "manifests", note: "Seven skill manifests, a few hundred tokens, travel in the first user message with the clock and the governed definitions." },
        { flow: "reason", note: "call_model 1: Claude asks for load_skill(\"morning-brief\")." },
        { flow: "manifests", note: "The skill's full body is loaded, once." },
        { flow: "reason", note: "call_model 2: Claude calls triage_inbox." },
        { flow: "dispatch", note: "dispatch_tools: triage_inbox is automatic." },
        { flow: "gateway", note: "mail_search_threads and mail_get_thread over MCP, on the practice mailbox." },
        { flow: "decide", note: "Is this email an attack? One noul per message; three real injections are flagged and quarantined; the model never sees their text.", state: "ppa_decision_log: attack" },
        { flow: "state", note: "The governed triage: categories, attention ranks, existing tasks." },
        { flow: "checkpoint", note: "Saved after the tool step." },
        { flow: "reason", note: "call_model 3: the brief, with the quarantined threads named and not opened." },
        { flow: "trace", note: "persist: the answer, the spans, the tokens.", state: "3 model calls · ~40k input tokens, 17k from cache" },
        { flow: "live", note: "The trace filled in as the nodes ran; the answer arrives whole." },
      ] },
    { id: "send", title: "A reply that needs approval", blurb: "Sending mail is a gated effect. The model drafts it; the harness pauses; the owner decides; the same run continues and the audit keeps approval and delivery apart.",
      steps: [
        { flow: "ask", note: "\"Reply to Stephanie Miller: I'll call her at 3pm. Send it.\"" },
        { flow: "post", note: "Same conversation, next turn." },
        { flow: "run", note: "agent.run." },
        { flow: "reason", note: "Claude reads the thread (mail_get_thread, automatic) and calls mail_send_message." },
        { flow: "gateway", note: "The read goes through MCP; the send does not run." },
        { flow: "draft", note: "draft_effects: the send is drafted with its recipient risk; human_review calls interrupt().", state: "ppa_action_audit: DRAFTED" },
        { flow: "checkpoint", note: "The paused run is saved." },
        { flow: "card", note: "The approval card: recipient, subject, body, risk, safe-mode effect." },
        { flow: "decision", note: "Approve." },
        { flow: "resume", note: "Command(resume): apply_effects runs the drafted call as approved, never as the model would reconstruct it." },
        { flow: "gateway", note: "mail_send_message over MCP. Practice workspace: simulated delivery, nobody is reached." },
        { flow: "audit", note: "EXECUTED, delivery recorded separately.", state: "ppa_action_audit: EXECUTED · delivered" },
        { flow: "reason", note: "call_model: the model is told the effect was applied and writes the confirmation." },
        { flow: "trace", note: "persist." },
      ] },
    { id: "timer", title: "A focus timer fires", blurb: "A Pomodoro is a real job on the real clock, stored in the database, so it survives a restart. When it fires, a routine turn summarises the session and a notification reaches the page.",
      steps: [
        { flow: "ask", note: "\"Start a Pomodoro on my first task.\"" },
        { flow: "post", note: "One turn." },
        { flow: "reason", note: "Claude calls pomodoro_start." },
        { flow: "dispatch", note: "pomodoro_start is automatic." },
        { flow: "arm", note: "A focus session row and an armed job with a fire time on the real clock.", state: "ppa_automation_queue: ARMED" },
        { flow: "checkpoint", note: "Saved." },
        { flow: null, note: "Twenty-five minutes pass. The scheduler thread polls the queue every half second." },
        { flow: "fire", note: "The job fires: a routine turn on the scripted responder, so it reports on time whatever the model service is doing." },
        { flow: "state", note: "The session is COMPLETED; parked distractions are collected.", state: "ppa_focus_sessions: COMPLETED" },
        { flow: "notify", note: "A notification: minutes done, what was parked, take a break." },
        { flow: "toast", note: "The page shows it at once; the browser too, when allowed." },
      ] },
  ],
};
