/* The reference architecture of the survey-paper appbook, as the running application is built. */
const SURVEY_REFARCH = {
  tiers: [
    { id: "people", title: "People and channel", note: "who asks, who approves twice" },
    { id: "control", title: "Control plane", note: "the harness owns the loop, the rules and the gates" },
    { id: "models", title: "Models", note: "one reasoning model, typed answers only" },
    { id: "services", title: "External services", note: "real scholarly search and page extraction" },
    { id: "data", title: "Data and state · Oracle AI Database 26ai", note: "an evidence library with vectors made inside the database" },
    { id: "output", title: "Output and observability", note: "the paper, and how it was made" },
  ],
  components: [
    { id: "person", tier: "people", col: 0, kind: "person", name: "Author", tech: "a subject, two approvals", note: "Names the subject and audience, approves the outline before anything is read, and approves the paper before it is published." },
    { id: "browser", tier: "people", col: 1, kind: "channel", icon: "browser", name: "Appbook page", tech: "vanilla JS · server-sent events", note: "The form, the outline to approve, live progress by section, the finished survey in place, the library search, the explorer." },
    { id: "api", tier: "control", col: 1, kind: "control", icon: "api", name: "Appbook API", tech: "FastAPI · uvicorn", note: "Starts and resumes runs on a thread, streams ledger lines, serves the paper as Markdown and HTML, and the read-only explorer." },
    { id: "graph", tier: "control", col: 2, kind: "control", icon: "loop", name: "Research graph", tech: "LangGraph · Send fan-out · max_concurrency 3", note: "scope → outline review → gather ×N → read → organise → write ×N → review → assemble → publication review → publish. One gather and one write task per section; a revise verdict can send the run back to gather once." },
    { id: "rules", tier: "control", col: 3, kind: "control", icon: "shield", name: "Harness rules", tech: "words · citations · resolution", note: "What the harness can count: at least 350 words and 3 citations per evidence section, every [S-id] resolves to a row, a round counter that bounds revision." },
    { id: "gates", tier: "control", col: 4, kind: "gate", name: "Two approval gates", tech: "interrupt() · Command(resume)", note: "outline_review, before a single page is read; publication_review, before a file is written. Each pauses the run with its state saved." },
    { id: "claude", tier: "models", col: 2, kind: "model", name: "Claude Opus 5.5", tech: "Anthropic API · JSON schema · streamed", note: "Scopes the paper, reads sources into typed notes, builds the framework and comparison table, writes each section from its evidence pack citing only [S-id]s it was given, referees the draft, writes the abstract." },
    { id: "tavily", tier: "services", col: 1, kind: "external", icon: "search", name: "Tavily search + extract", tech: "scholarly domains · full page text", note: "Search on arXiv, OpenReview, ACL, ACM, IEEE and similar venues; extract reads the best pages in full." },
    { id: "library", tier: "data", col: 1, kind: "store", icon: "vector", name: "Evidence library", tech: "SURVEY_SOURCES · VECTOR(384) · ONNX in-database", note: "Every page read, with its text and an embedding computed inside the database as the row is stored. Asked by meaning with VECTOR_DISTANCE; one key per work, so arXiv abs, html and pdf are one source." },
    { id: "notes", tier: "data", col: 2, kind: "store", icon: "doc", name: "Notes and drafts", tech: "SURVEY_NOTES · SECTIONS · REVIEWS", note: "Typed reading of each source (contribution, method, evidence, claims, relevance), the current draft of each section with its counts, each referee pass." },
    { id: "papers", tier: "data", col: 3, kind: "store", icon: "database", name: "Papers", tech: "SURVEY_PAPERS · outline · taxonomy · markdown · html", note: "One row per paper with its plan, its framework and the assembled text." },
    { id: "checkpoints", tier: "data", col: 4, kind: "store", icon: "checkpoint", name: "Checkpoints", tech: "OracleSaver · one thread per paper", note: "A checkpoint after every step. LangGraph keeps the writes of tasks that finished, so a continued run redoes only what did not." },
    { id: "files", tier: "output", col: 3, kind: "output", name: "Published paper", tech: "Markdown + HTML files", note: "Numbered citations in order of first use, a reference list in which every entry is a page the harness read, and a closing note on how the paper was made." },
    { id: "ledger", tier: "output", col: 0, kind: "observe", icon: "ledger", name: "Ledger", tech: "SURVEY_LEDGER · SSE to the page", note: "Every step of every run, pushed to the page as it happens." },
    { id: "explorer", tier: "output", col: 1, kind: "observe", icon: "database", name: "Data explorer", tech: "read-only · allowlisted tables", note: "Every table above, newest rows first, from the page." },
  ],
  flows: [
    { id: "ask", from: "person", to: "browser", label: "subject · audience", kind: "request" },
    { id: "post", from: "browser", to: "api", label: "POST /api/papers", kind: "request" },
    { id: "start", from: "api", to: "graph", label: "start_paper · resume_paper", kind: "control" },
    { id: "reason", from: "graph", to: "claude", label: "typed requests → JSON", kind: "data", dx: -74, dy: 4 },
    { id: "search", from: "graph", to: "tavily", label: "gather: search, then extract", kind: "data", dx: -100, dy: 44 },
    { id: "store", from: "graph", to: "library", label: "store page + embedding", kind: "store", dx: -150, dy: -8 },
    { id: "similar", from: "library", to: "graph", label: "nearest sources by meaning", kind: "store", dx: 120, dy: -10 },
    { id: "notes", from: "graph", to: "notes", label: "notes · drafts · reviews", kind: "store", dx: 78, dy: 26 },
    { id: "paper", from: "graph", to: "papers", label: "outline · taxonomy · text", kind: "store", dx: 120, dy: -6 },
    { id: "checkpoint", from: "graph", to: "checkpoints", label: "checkpoint after every step", kind: "store", dx: 150, dy: 40 },
    { id: "check", from: "graph", to: "rules", label: "drafts to check", kind: "control", dy: -8 },
    { id: "verdict", from: "rules", to: "graph", label: "problems · round", kind: "control", dy: 14 },
    { id: "interrupt", from: "rules", to: "gates", label: "interrupt()", kind: "control", dy: -8 },
    { id: "card", from: "gates", to: "browser", label: "outline · paper to approve (SSE)", kind: "data", dy: -6, dx: 60 },
    { id: "decision", from: "browser", to: "gates", label: "approve · revise · reject", kind: "request", dy: 16, dx: -60 },
    { id: "resume", from: "gates", to: "graph", label: "Command(resume=decision)", kind: "control", dy: 30 },
    { id: "publish", from: "papers", to: "files", label: "publish: .md and .html", kind: "store" },
    { id: "log", from: "graph", to: "ledger", label: "every step", kind: "store", dx: -70, dy: 50 },
    { id: "trace", from: "ledger", to: "browser", label: "live trace (SSE)", kind: "event", dx: -60, dy: -70 },
    { id: "explore", from: "explorer", to: "library", label: "read-only rows", kind: "data", dx: 30 },
    { id: "read", from: "browser", to: "api", label: "GET paper.md · paper.html", kind: "request", dx: 150, dy: 30 },
  ],
  runs: [
    { id: "write", title: "Write a survey, with both gates", blurb: "Half a minute to an outline, then ten to fifteen minutes and about forty model calls to a reviewed, assembled paper.",
      steps: [
        { flow: "ask", note: "\"agent harness engineering\", for researchers and engineers building agent systems." },
        { flow: "post", note: "The page posts the subject.", state: "SURVEY_PAPERS: STARTED" },
        { flow: "start", note: "A thread runs start_paper." },
        { flow: "reason", note: "scope: research questions, inclusion criteria, an outline of 12 sections, each with its own search queries." },
        { flow: "paper", note: "The outline is stored.", state: "SURVEY_PAPERS: OUTLINED" },
        { flow: "checkpoint", note: "Saved before the first pause.", state: "checkpoints: 3" },
        { flow: "interrupt", note: "outline_review: nothing has been read, nothing paid for beyond one call." },
        { flow: "card", note: "The outline, the questions and the criteria, to approve or revise with a note." },
        { flow: "decision", note: "Approve." },
        { flow: "resume", note: "after_outline_review returns one Send per section that needs evidence." },
        { flow: "search", note: "gather ×10, three at a time: two searches per section on scholarly venues, the best six pages read in full." },
        { flow: "store", note: "Each page becomes a row with an embedding made inside the database. Two sections finding the same page: the unique key keeps it once.", state: "SURVEY_SOURCES: ~60 rows" },
        { flow: "reason", note: "read: unread sources four per call, on a small pool, into typed notes." },
        { flow: "notes", note: "One note per source: kind, year, venue, contribution, method, evidence, claims, relevance." },
        { flow: "reason", note: "organise: the framework, the comparison table, the open questions, from the notes." },
        { flow: "similar", note: "write ×12: each section's evidence pack is its own sources plus the nearest by meaning; framework and outlook may cite the whole library." },
        { flow: "reason", note: "write: prose that compares works and cites only [S-id]s in its pack; any other citation is stripped." },
        { flow: "notes", note: "Drafts stored with word and citation counts." },
        { flow: "check", note: "Harness rules: words, citations, every citation resolves." },
        { flow: "reason", note: "review: a referee pass names unsupported claims, missing works, and queries for sections that need more evidence." },
        { flow: "verdict", note: "revise, with queries, and a round left: back to gather for those sections; then read, organise, write again.", state: "round: 2" },
        { flow: "reason", note: "assemble: citations numbered in order of first use, references from the library, an abstract." },
        { flow: "paper", note: "Markdown and HTML stored on the paper row.", state: "SURVEY_PAPERS: ASSEMBLED" },
        { flow: "interrupt", note: "publication_review." },
        { flow: "card", note: "Title, size, abstract; the paper is already readable in place." },
        { flow: "decision", note: "Approve." },
        { flow: "publish", note: "The files are written.", state: "SURVEY_PAPERS: PUBLISHED" },
        { flow: "trace", note: "The page's trace filled in live; the survey shows on the Write a survey view." },
      ] },
    { id: "resume", title: "A stopped run continues", blurb: "The process dies while gather tasks are running. LangGraph kept the writes of the tasks that finished; a continued run redoes only the two that did not.",
      steps: [
        { flow: "search", note: "Ten gather tasks, three at a time." },
        { flow: "store", note: "Eight finish and their rows are in the library." },
        { flow: null, note: "The process stops. The step's checkpoint was not written, but the finished tasks' writes were saved as pending writes." },
        { flow: "post", note: "POST /api/papers/{id}/continue." },
        { flow: "start", note: "continue_paper(None)." },
        { flow: "checkpoint", note: "The last checkpoint and the pending writes are read back: resume from ['gather', 'gather']." },
        { flow: "search", note: "Only the two unfinished sections search again; pages already in the library are skipped by their key." },
        { flow: "reason", note: "read, organise, write, review, assemble follow as usual." },
      ] },
  ],
};
