/* The reference architecture of the trip workflow appbook, as the running application is built. */
const TRIP_REFARCH = {
  tiers: [
    { id: "people", title: "People and channel", note: "who asks, who decides" },
    { id: "control", title: "Control plane", note: "the harness owns the shape of the run" },
    { id: "models", title: "Models", note: "one reasons, one decides" },
    { id: "services", title: "Tools and external services", note: "real search; a stand-in system of record" },
    { id: "data", title: "Data and state · Oracle AI Database 26ai", note: "one schema, PPA_ADVANCED" },
    { id: "observe", title: "Observability", note: "what happened, live and after" },
  ],
  components: [
    { id: "traveller", tier: "people", col: 0, kind: "person", name: "Traveller", tech: "one sentence, one decision", note: "Writes what they want in plain words, approves or changes the itinerary, and is asked again only when a fallback is not like for like." },
    { id: "browser", tier: "people", col: 1, kind: "channel", icon: "browser", name: "Appbook page", tech: "vanilla JS · server-sent events", note: "A no-build page: the form, the itinerary card with approve, change and reject, the live trace, the explorer." },
    { id: "api", tier: "control", col: 1, kind: "control", icon: "api", name: "Appbook API", tech: "FastAPI · uvicorn", note: "Starts runs on a thread, resumes them with the traveller's decision, streams ledger lines as events, serves the read-only explorer." },
    { id: "graph", tier: "control", col: 2, kind: "control", icon: "loop", name: "Trip graph", tech: "LangGraph StateGraph · 16 nodes", note: "recall → understand → three searches in parallel → join → plan → review → book flight, hotel, car → compensate → confirm. Plain node functions over a typed state." },
    { id: "gate", tier: "control", col: 3, kind: "gate", name: "Approval gate", tech: "interrupt() · Command(resume)", note: "The run stops with its state saved. Whatever resumes it is the traveller's decision, and the same run continues from its checkpoint." },
    { id: "claude", tier: "models", col: 2, kind: "model", name: "Claude Opus 5.5", tech: "Anthropic API · JSON schema on every call", note: "Reasons and writes: understands the request, turns search results into typed offers, composes the itinerary. Never parses prose; the harness recomputes every total." },
    { id: "jev", tier: "models", col: 3, kind: "decide", name: "Jev · System One", tech: "Typesafe API · noul and choice questions", note: "Answers closed questions with a probability in a third of a second: which memories bear on the request, which pages to read, whether an offer honours a preference, whether a fallback is like for like. The harness owns each threshold." },
    { id: "tavily", tier: "services", col: 1, kind: "external", icon: "search", name: "Tavily web search", tech: "search_depth advanced · 8 results", note: "Real pages about flights, hotels and cars. Every page read is kept as evidence; prices from pages are indicative and carry a confidence." },
    { id: "booking", tier: "services", col: 4, kind: "tool", icon: "booking", name: "Booking system of record", tech: "TRIP_BOOKINGS · idempotency keys", note: "Stands in for the providers. The same request twice returns the first confirmation; a fault switch lets a lesson make a provider answer sold out." },
    { id: "memory", tier: "data", col: 0, kind: "store", icon: "memory", name: "Oracle Agent Memory", tech: "TRIPMEM_* · ONNX embeddings in the database", note: "What the traveller prefers, across trips, recalled by meaning. Written on purpose by the harness, once per statement." },
    { id: "tables", tier: "data", col: 1, kind: "store", icon: "database", name: "Workflow tables", tech: "TRIP_REQUESTS · EVIDENCE · OFFERS · BOOKINGS", note: "The request, every page read with its screening scores, every typed offer, and the bookings: the outside world's truth, separate from the run's control flow." },
    { id: "checkpoints", tier: "data", col: 2, kind: "store", icon: "checkpoint", name: "Checkpoints", tech: "OracleSaver · one thread per trip", note: "A checkpoint after every node. A paused run resumes from here; a dead process is continued from here." },
    { id: "decisions", tier: "data", col: 3, kind: "store", icon: "decide", name: "Decision log", tech: "TRIP_DECISIONS", note: "Every question put to System One with its time, tokens and answers." },
    { id: "ledger", tier: "observe", col: 0, kind: "observe", icon: "ledger", name: "Ledger", tech: "TRIP_LEDGER · SSE to the page", note: "Every step of every run, written by the nodes and pushed to the page as it happens." },
    { id: "explorer", tier: "observe", col: 2, kind: "observe", icon: "vector", name: "Data explorer", tech: "read-only · allowlisted tables", note: "Every table above, newest rows first, from the page." },
  ],
  flows: [
    { id: "ask", from: "traveller", to: "browser", label: "one sentence", kind: "request" },
    { id: "post", from: "browser", to: "api", label: "POST /api/trips", kind: "request" },
    { id: "start", from: "api", to: "graph", label: "start_trip · resume_trip", kind: "control" },
    { id: "recall", from: "graph", to: "memory", label: "recall · remember", kind: "store", dx: -110, dy: -6 },
    { id: "decide", from: "graph", to: "jev", label: "closed questions → probabilities", kind: "control", dx: 70, dy: 4 },
    { id: "reason", from: "graph", to: "claude", label: "typed requests → JSON", kind: "data", dx: -78, dy: 4 },
    { id: "search", from: "graph", to: "tavily", label: "three searches, in parallel", kind: "data", dx: -96, dy: 44 },
    { id: "evidence", from: "graph", to: "tables", label: "evidence · offers · request", kind: "store", dx: 6, dy: -40 },
    { id: "checkpoint", from: "graph", to: "checkpoints", label: "checkpoint after every node", kind: "store", dx: 92, dy: 26 },
    { id: "interrupt", from: "graph", to: "gate", label: "interrupt(): the itinerary", kind: "control", dy: -8 },
    { id: "card", from: "gate", to: "browser", label: "itinerary card · SSE", kind: "data", dy: -6 },
    { id: "decision", from: "browser", to: "gate", label: "approve · change · reject", kind: "request", dy: 12 },
    { id: "resume", from: "gate", to: "graph", label: "Command(resume=decision)", kind: "control", dy: 12 },
    { id: "book", from: "graph", to: "booking", label: "book · cancel (idempotency key)", kind: "data", dx: 40, dy: -44 },
    { id: "bookrow", from: "booking", to: "tables", label: "TRIP_BOOKINGS row", kind: "store", dy: 14 },
    { id: "log", from: "graph", to: "ledger", label: "every step", kind: "store", dx: -60, dy: 40 },
    { id: "trace", from: "ledger", to: "browser", label: "live trace (SSE)", kind: "event", dx: -70, dy: -60 },
    { id: "logdecision", from: "jev", to: "decisions", label: "time · tokens · answers", kind: "store" },
    { id: "explore", from: "explorer", to: "tables", label: "read-only rows", kind: "data", dx: 20, dy: 4 },
  ],
  runs: [
    { id: "book", title: "Plan and book a trip", blurb: "One sentence in; three searches at once; an itinerary to approve; three bookings in order. About a minute to the gate, seconds after it.",
      steps: [
        { flow: "ask", note: "\"Book me a trip from London to Lisbon, 12 to 15 October, flight, hotel and car, budget £900.\"" },
        { flow: "post", note: "The page posts the text and the traveller's id.", state: "TRIP_REQUESTS: STARTED" },
        { flow: "start", note: "A thread runs start_trip; the page keeps working." },
        { flow: "recall", note: "recall_preferences: the traveller's memories, by meaning." },
        { flow: "decide", note: "Which memories bear on this request? noul per memory; keep at or above 0.6. \"Allergic to shellfish\" scores 0.5 and is dropped.", state: "TRIP_DECISIONS: preferences" },
        { flow: "reason", note: "understand: the sentence becomes a typed request (origin, dates, nights, wants, budget)." },
        { flow: "checkpoint", note: "LangGraph saves the state after the node.", state: "checkpoints: 2" },
        { flow: "search", note: "search_flight, search_hotel and search_car run in the same step." },
        { flow: "decide", note: "Which pages are about this trip, and which try to give the assistant orders? Two noul per page; a page with an order is kept as evidence and never shown to Claude.", state: "TRIP_EVIDENCE: relevance · attack · kept" },
        { flow: "reason", note: "extract offers: the pages worth reading become typed offers, each naming its page, with a confidence." },
        { flow: "evidence", note: "Every page and every offer is stored.", state: "TRIP_OFFERS: ~40 rows" },
        { flow: "reason", note: "plan: one offer per component, alternatives named; the harness adds up the totals." },
        { flow: "decide", note: "Does each chosen offer honour the preference it concerns? A \"does not\" becomes a caveat.", state: "itinerary.checks" },
        { flow: "checkpoint", note: "Saved before the pause.", state: "checkpoints: 7" },
        { flow: "interrupt", note: "review: interrupt() stops the run. Nothing is booked." },
        { flow: "card", note: "The itinerary card: choices, totals, caveats, preference verdicts, evidence links." },
        { flow: "decision", note: "The traveller approves." },
        { flow: "resume", note: "The same run continues from its checkpoint." },
        { flow: "book", note: "book_flight, then book_hotel, then book_car: a saga in a fixed order, each safe to run twice.", state: "key = trip:component:offer:attempt" },
        { flow: "bookrow", note: "Three CONFIRMED rows with confirmations." },
        { flow: "recall", note: "confirm: the trip is remembered for next time." },
        { flow: "log", note: "Every node wrote its line as it ran." },
        { flow: "trace", note: "The page's trace filled in live; status: booked." },
      ] },
    { id: "fail", title: "A provider fails: compensation and like-for-like", blurb: "The hotel provider answers sold out after the flight is booked. The harness cancels the flight, swaps in the next hotel, and asks System One whether the traveller must be asked again.",
      steps: [
        { flow: "decision", note: "The traveller approves the itinerary." },
        { flow: "resume", note: "The saga starts." },
        { flow: "book", note: "book_flight: CONFIRMED." },
        { flow: "book", note: "book_hotel: the provider answers sold_out (a fault armed in chapter 5).", state: "TRIP_BOOKINGS: FAILED row" },
        { flow: "book", note: "compensate: the flight booking is cancelled." },
        { flow: "bookrow", note: "flight CANCELLED, hotel FAILED." },
        { flow: "decide", note: "Is the next hotel like for like: same kind of offer, price within a fifth, no worse against the preferences? One noul; the cut is 0.7 and the total must stay within budget.", state: "TRIP_DECISIONS: like_for_like" },
        { flow: "interrupt", note: "Below the cut: the run pauses at review with the fallback plan and a new caveat." },
        { flow: "card", note: "The traveller sees the fallback hotel and the caveat." },
        { flow: "decision", note: "Approve again. (At or above the cut, this step and the two before it do not happen: the saga runs again on the approval already given.)" },
        { flow: "resume", note: "A new attempt number means new idempotency keys." },
        { flow: "book", note: "flight, fallback hotel, car: CONFIRMED." },
        { flow: "log", note: "compensate: fallback · like_for_like · next" },
      ] },
    { id: "crash", title: "Crash and resume", blurb: "The process dies inside book_flight, after the provider confirmed but before LangGraph saved that step. A new process continues the same trip.",
      steps: [
        { flow: "decision", note: "The traveller approves." },
        { flow: "resume", note: "The saga starts." },
        { flow: "book", note: "book_flight: the provider confirms." },
        { flow: "bookrow", note: "The CONFIRMED row is committed." },
        { flow: null, note: "The process exits here (os._exit). No checkpoint was written for book_flight.", state: "last checkpoint: after review" },
        { flow: "post", note: "A new process: POST /api/trips/{id}/continue." },
        { flow: "start", note: "continue_trip(None): LangGraph picks up at the last checkpoint." },
        { flow: "checkpoint", note: "The state before book_flight is read back." },
        { flow: "book", note: "book_flight runs again; the same idempotency key returns the first confirmation. replayed = true." },
        { flow: "book", note: "book_hotel and book_car follow." },
        { flow: "log", note: "The ledger shows book_flight twice: once booked, once replayed." },
      ] },
  ],
};
